//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Errors
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using TofuPilot.Models.Components;
    using TofuPilot.Utils;
    
    /// <summary>
    /// Forbidden error
    /// </summary>
    public class ErrorFORBIDDEN : Exception
    {

        /// <summary>
        /// The error message
        /// </summary>
        [JsonProperty("message")]
        private string? _message { get; set; }
        public override string Message { get {return _message ?? "";} }

        /// <summary>
        /// The error code
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; } = default!;

        /// <summary>
        /// An array of issues that were responsible for the error
        /// </summary>
        [JsonProperty("issues")]
        public List<ErrorFORBIDDENIssue>? Issues { get; set; }
    }
}