//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by TofuPilot SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Utils
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json;
    using System.Text.Json.Serialization;

    public class AnyDeserializer : JsonConverter<Dictionary<string, object>>
    {
        public override Dictionary<string, object>? Read(
            ref Utf8JsonReader reader,
            Type typeToConvert,
            JsonSerializerOptions options
        )
        {
            if (reader.TokenType != JsonTokenType.StartObject)
            {
                throw new JsonException("Could not deserialize token into dictionary");
            }

            using var doc = JsonDocument.ParseValue(ref reader);
            return ParseElementIntoDictionary(doc.RootElement);
        }

        private Dictionary<string, object?> ParseElementIntoDictionary(JsonElement element)
        {
            var dict = new Dictionary<string, object?>();

            foreach (var property in element.EnumerateObject())
            {
                dict[property.Name] = ParseValue(property.Value);
            }

            return dict;
        }

        private List<object?> ParseElementIntoList(JsonElement element)
        {
            var list = new List<object?>();

            foreach (var item in element.EnumerateArray())
            {
                list.Add(ParseValue(item));
            }

            return list;
        }

        private object? ParseValue(JsonElement element)
        {
            switch (element.ValueKind)
            {
                case JsonValueKind.Object:
                    return ParseElementIntoDictionary(element);
                case JsonValueKind.Array:
                    return ParseElementIntoList(element);
                case JsonValueKind.String:
                    return element.GetString();
                case JsonValueKind.Number:
                    if (element.TryGetInt64(out long l))
                        return l;
                    return element.GetDouble();
                case JsonValueKind.True:
                    return true;
                case JsonValueKind.False:
                    return false;
                case JsonValueKind.Null:
                case JsonValueKind.Undefined:
                default:
                    return null;
            }
        }

        public override void Write(Utf8JsonWriter writer, Dictionary<string, object> value, JsonSerializerOptions options)
        {
            throw new NotSupportedException();
        }
    }
}
