//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by TofuPilot SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Utils
{
    using System;
    using System.Globalization;
    using System.Numerics;
    using System.Text.Json;
    using System.Text.Json.Serialization;

    internal class BigIntStrConverter : JsonConverter<BigInteger>
    {
        public override BigInteger Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value == null)
            {
                return default;
            }

            try
            {
                return BigInteger.Parse(value);
            }
            catch (System.FormatException ex)
            {
                throw new JsonException("Could not parse BigInteger", ex);
            }
        }

        public override void Write(Utf8JsonWriter writer, BigInteger value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString(CultureInfo.InvariantCulture));
        }
    }
}
