//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by TofuPilot SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TofuPilot.Utils
{
    internal class EnumConverter : JsonConverterFactory
    {
        public override bool CanConvert(System.Type typeToConvert)
        {
            var nullableType = Nullable.GetUnderlyingType(typeToConvert);
            if (nullableType != null)
            {
                return nullableType.IsEnum;
            }

            return typeToConvert.IsEnum;
        }

        public override JsonConverter CreateConverter(System.Type typeToConvert, JsonSerializerOptions options)
        {
            var enumType = Nullable.GetUnderlyingType(typeToConvert) ?? typeToConvert;
            var converterType = typeof(EnumConverterInner<>).MakeGenericType(enumType);
            return (JsonConverter)Activator.CreateInstance(converterType)!;
        }

        private class EnumConverterInner<T> : JsonConverter<T> where T : struct, Enum
        {
            public override T Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options)
            {
                if (reader.TokenType == JsonTokenType.Null)
                {
                    return default;
                }

                var value = reader.GetString();
                if (value == null)
                {
                    return default;
                }

                var objectType = typeToConvert;
                var extensionType = System.Type.GetType(objectType.FullName + "Extension");

                if (Nullable.GetUnderlyingType(objectType) != null)
                {
                    objectType = Nullable.GetUnderlyingType(objectType)!;
                    extensionType = System.Type.GetType(objectType!.FullName + "Extension");
                }

                if (extensionType == null)
                {
                    if (Enum.TryParse<T>(value, out var result))
                    {
                        return result;
                    }
                    return default;
                }

                var method = extensionType.GetMethod("ToEnum");
                if (method == null)
                {
                    throw new Exception($"Unable to find ToEnum method on {extensionType.FullName}");
                }

                try
                {
                    return (T)method.Invoke(null, new[] { value })!;
                }
                catch (System.Reflection.TargetInvocationException e)
                {
                    throw new JsonException("Unable to convert value to enum", e);
                }
            }

            public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
            {
                var extensionType = System.Type.GetType(value.GetType().FullName + "Extension");
                if (extensionType == null)
                {
                    writer.WriteStringValue(value.ToString());
                    return;
                }

                writer.WriteStringValue(Utilities.ToString(value));
            }
        }
    }
}
