//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using TofuPilot.Utils;
    using System.Collections.Generic;
    
    public class AttachmentDeleteRequest
    {

        /// <summary>
        /// Upload IDs to delete
        /// </summary>
        [ApiMetadata("queryParam:style=form,explode=true,name=ids")]
        public List<string> Ids { get; set; } = default!;
    }
}