//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    
    public class BatchUpdateRequest
    {

        /// <summary>
        /// Current batch number to update.
        /// </summary>
        [ApiMetadata("pathParam:style=simple,explode=false,name=number")]
        public string Number { get; set; } = default!;

        [ApiMetadata("request:mediaType=application/json")]
        public BatchUpdateRequestBody RequestBody { get; set; } = default!;
    }
}