//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Batches retrieved successfully
    /// </summary>
    public class BatchListResponse
    {

        /// <summary>
        /// Array of batches matching the query.
        /// </summary>
        [JsonProperty("data")]
        public List<BatchListData> Data { get; set; } = default!;

        /// <summary>
        /// Pagination metadata.
        /// </summary>
        [JsonProperty("meta")]
        public BatchListMeta Meta { get; set; } = default!;
    }
}