//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    
    /// <summary>
    /// Part information with revision details for this unit.
    /// </summary>
    public class BatchGetPart
    {

        /// <summary>
        /// Part ID.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Part number.
        /// </summary>
        [JsonProperty("number")]
        public string Number { get; set; } = default!;

        /// <summary>
        /// Part name.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Revision information for this unit.
        /// </summary>
        [JsonProperty("revision")]
        public BatchGetRevision Revision { get; set; } = default!;
    }
}