//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Severity of the build log line.
    /// </summary>
    public enum DeploymentGetLevel
    {
        [JsonPropertyName("DEBUG")]
        Debug,
        [JsonPropertyName("INFO")]
        Info,
        [JsonPropertyName("WARNING")]
        Warning,
        [JsonPropertyName("ERROR")]
        Error,
        [JsonPropertyName("CRITICAL")]
        Critical,
    }

    public static class DeploymentGetLevelExtension
    {
        public static string Value(this DeploymentGetLevel value)
        {
            return ((JsonPropertyNameAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyNameAttribute), false)[0]).Name ?? value.ToString();
        }

        public static DeploymentGetLevel ToEnum(this string value)
        {
            foreach(var field in typeof(DeploymentGetLevel).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyNameAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyNameAttribute;
                if (attribute != null && attribute.Name == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is DeploymentGetLevel)
                    {
                        return (DeploymentGetLevel)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum DeploymentGetLevel");
        }
    }

}