//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Deployment environment.
    /// </summary>
    public enum DeploymentListDataEnvironment
    {
        [JsonPropertyName("production")]
        Production,
        [JsonPropertyName("preview")]
        Preview,
        [JsonPropertyName("development")]
        Development,
    }

    public static class DeploymentListDataEnvironmentExtension
    {
        public static string Value(this DeploymentListDataEnvironment value)
        {
            return ((JsonPropertyNameAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyNameAttribute), false)[0]).Name ?? value.ToString();
        }

        public static DeploymentListDataEnvironment ToEnum(this string value)
        {
            foreach(var field in typeof(DeploymentListDataEnvironment).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyNameAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyNameAttribute;
                if (attribute != null && attribute.Name == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is DeploymentListDataEnvironment)
                    {
                        return (DeploymentListDataEnvironment)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum DeploymentListDataEnvironment");
        }
    }

}