//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Deployments retrieved successfully
    /// </summary>
    public class DeploymentListResponse
    {

        /// <summary>
        /// The list of deployments matching the request.
        /// </summary>
        [JsonPropertyName("data")]
        public List<DeploymentListData> Data { get; set; } = default!;

        /// <summary>
        /// Pagination metadata.
        /// </summary>
        [JsonPropertyName("meta")]
        public DeploymentListMeta Meta { get; set; } = default!;
    }
}