//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    
    /// <summary>
    /// User who created the deployment. Null for system-created deployments.
    /// </summary>
    public class DeploymentGetCreatedByUser
    {

        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        [JsonPropertyName("image")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? Image { get; set; }
    }
}