//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Deployment retrieved successfully
    /// </summary>
    public class DeploymentGetResponse
    {

        /// <summary>
        /// Unique identifier for the deployment.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Deployment environment.
        /// </summary>
        [JsonPropertyName("environment")]
        public DeploymentGetEnvironment Environment { get; set; } = default!;

        /// <summary>
        /// How the deployment was triggered.
        /// </summary>
        [JsonPropertyName("trigger")]
        public DeploymentGetTrigger Trigger { get; set; } = default!;

        /// <summary>
        /// Build status of the deployment.
        /// </summary>
        [JsonPropertyName("status")]
        public DeploymentGetStatus Status { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the deployment was created.
        /// </summary>
        [JsonPropertyName("deployed_at")]
        public DateTime DeployedAt { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the build started. Null if not started.
        /// </summary>
        [JsonPropertyName("started_at")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DateTime? StartedAt { get; set; }

        /// <summary>
        /// ISO 8601 timestamp when the build ended. Null if not ended.
        /// </summary>
        [JsonPropertyName("ended_at")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DateTime? EndedAt { get; set; }

        /// <summary>
        /// URL of the built artifact. Null if not built.
        /// </summary>
        [JsonPropertyName("artifact_url")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? ArtifactUrl { get; set; }

        /// <summary>
        /// SHA-256 checksum of the artifact. Null if not built.
        /// </summary>
        [JsonPropertyName("artifact_sha256")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? ArtifactSha256 { get; set; }

        /// <summary>
        /// Size of the artifact in bytes. Null if not built.
        /// </summary>
        [JsonPropertyName("artifact_size_bytes")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public double? ArtifactSizeBytes { get; set; }

        /// <summary>
        /// Deployment mode.
        /// </summary>
        [JsonPropertyName("deployment_mode")]
        public DeploymentGetDeploymentMode DeploymentMode { get; set; } = default!;

        /// <summary>
        /// Target platform. Null if unspecified.
        /// </summary>
        [JsonPropertyName("platform")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? Platform { get; set; }

        /// <summary>
        /// Procedure language. Null if unspecified.
        /// </summary>
        [JsonPropertyName("language")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? Language { get; set; }

        /// <summary>
        /// Runtime version. Null if unspecified.
        /// </summary>
        [JsonPropertyName("runtime_version")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? RuntimeVersion { get; set; }

        /// <summary>
        /// Procedure this deployment targets.
        /// </summary>
        [JsonPropertyName("procedure")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DeploymentGetProcedure? Procedure { get; set; }

        /// <summary>
        /// User who created the deployment. Null for system-created deployments.
        /// </summary>
        [JsonPropertyName("created_by_user")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DeploymentGetCreatedByUser? CreatedByUser { get; set; }

        /// <summary>
        /// Git commit the deployment was built from. Null for non-git deployments.
        /// </summary>
        [JsonPropertyName("commit")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DeploymentGetCommit? Commit { get; set; }

        /// <summary>
        /// Stations linked to the procedure, with per-station push state. pushed_at is null when this deployment has not been pushed to that station.
        /// </summary>
        [JsonPropertyName("stations")]
        public List<DeploymentGetStations> Stations { get; set; } = default!;

        /// <summary>
        /// Build log lines for this deployment, ordered by sequence. Empty if the build has not produced logs.
        /// </summary>
        [JsonPropertyName("build_logs")]
        public List<DeploymentGetBuildLogs> BuildLogs { get; set; } = default!;
    }
}