//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Git commit the deployment was built from. Null for non-git deployments.
    /// </summary>
    public class DeploymentGetCommit
    {

        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        [JsonPropertyName("sha")]
        public string Sha { get; set; } = default!;

        [JsonPropertyName("message")]
        public string Message { get; set; } = default!;

        [JsonPropertyName("author_username")]
        public string AuthorUsername { get; set; } = default!;

        [JsonPropertyName("author_avatar_url")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? AuthorAvatarUrl { get; set; }

        [JsonPropertyName("committed_at")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DateTime? CommittedAt { get; set; }

        [JsonPropertyName("branch")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DeploymentGetBranch? Branch { get; set; }

        [JsonPropertyName("repository")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DeploymentGetRepository? Repository { get; set; }
    }
}