//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    
    public class ImportTabularRequest
    {

        /// <summary>
        /// ID of a previously uploaded tabular file.
        /// </summary>
        [JsonPropertyName("upload_id")]
        public string UploadId { get; set; } = default!;

        /// <summary>
        /// Procedure to attach the imported run to. Always overrides any procedure referenced in the file. Create the procedure in the app first, then find the auto-generated ID on the procedure page.
        /// </summary>
        [JsonPropertyName("procedure_id")]
        public string ProcedureId { get; set; } = default!;

        /// <summary>
        /// Inline column mapping describing how source columns feed TofuPilot fields. Provide this OR template_id, not both.
        /// </summary>
        [JsonPropertyName("mapping")]
        public ImportTabularMapping? Mapping { get; set; }

        /// <summary>
        /// ID of a saved mapping template to apply. Provide this OR mapping, not both.
        /// </summary>
        [JsonPropertyName("template_id")]
        public string? TemplateId { get; set; }
    }
}