//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    
    public class ImportTabularMeasurements1
    {

        [JsonPropertyName("layout")]
        public string Layout { get; set; } = default!;

        [JsonPropertyName("nameColumn")]
        public string NameColumn { get; set; } = default!;

        [JsonPropertyName("valueColumn")]
        public string ValueColumn { get; set; } = default!;

        [JsonPropertyName("unitsColumn")]
        public string? UnitsColumn { get; set; }

        [JsonPropertyName("lowerColumn")]
        public string? LowerColumn { get; set; }

        [JsonPropertyName("upperColumn")]
        public string? UpperColumn { get; set; }

        [JsonPropertyName("outcomeColumn")]
        public string? OutcomeColumn { get; set; }

        [JsonPropertyName("phaseColumn")]
        public string? PhaseColumn { get; set; }
    }
}