//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System.Collections.Generic;
    
    public class ImportStructuredResults
    {

        /// <summary>
        /// Upload ID this result corresponds to.
        /// </summary>
        [JsonPropertyName("upload_id")]
        public string UploadId { get; set; } = default!;

        /// <summary>
        /// Whether the file was imported successfully.
        /// </summary>
        [JsonPropertyName("success")]
        public bool Success { get; set; } = default!;

        /// <summary>
        /// ID of the created run (present when success is true). For a multi-run file this is the first run; see `ids`.
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get; set; }

        /// <summary>
        /// All run ids created from the file. Present when the file produced more than one run.
        /// </summary>
        [JsonPropertyName("ids")]
        public List<string>? Ids { get; set; }

        /// <summary>
        /// Error message (present when success is false).
        /// </summary>
        [JsonPropertyName("error")]
        public string? Error { get; set; }
    }
}