//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    
    public class ImportCreateFromFilesItems
    {

        /// <summary>
        /// ID of a previously uploaded file (via Initialize and Finalize upload).
        /// </summary>
        [JsonPropertyName("upload_id")]
        public string UploadId { get; set; } = default!;

        /// <summary>
        /// Source format of the uploaded file. OPENHTF for OpenHTF JSON logs; WATS for Virinco WATS WSJF (JSON); WSXF for WATS WSXF (XML); ATML for IEEE 1671 ATML Test Results (XML); TESTSTAND for NI TestStand native XML reports; STDF for binary STDF V4 datalogs; ATDF for ATDF (the ASCII text form of STDF). For CSV/tabular files use the dedicated tabular import endpoint.
        /// </summary>
        [JsonPropertyName("importer")]
        public ImportCreateFromFilesImporter Importer { get; set; } = default!;
    }
}