//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System.Collections.Generic;
    
    public class ImportTabularMeasurements2
    {

        [JsonPropertyName("layout")]
        public string Layout { get; set; } = default!;

        [JsonPropertyName("columns")]
        public List<ImportTabularColumns> Columns { get; set; } = default!;
    }
}