//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Log retrieved successfully
    /// </summary>
    public class LogGetResponse
    {

        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        [JsonPropertyName("level")]
        public LogGetLevel Level { get; set; } = default!;

        [JsonPropertyName("message")]
        public string Message { get; set; } = default!;

        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        [JsonPropertyName("source_file")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? SourceFile { get; set; }

        [JsonPropertyName("line_number")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public long? LineNumber { get; set; }

        [JsonPropertyName("run")]
        public LogGetRun Run { get; set; } = default!;

        [JsonPropertyName("unit")]
        public LogGetUnit Unit { get; set; } = default!;

        [JsonPropertyName("procedure")]
        public LogGetProcedure Procedure { get; set; } = default!;

        [JsonPropertyName("created_by_user")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public LogGetCreatedByUser? CreatedByUser { get; set; }

        [JsonPropertyName("created_by_station")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public LogGetCreatedByStation? CreatedByStation { get; set; }
    }
}