//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    
    /// <summary>
    /// Unit information for this log entry.
    /// </summary>
    public class LogListUnit
    {

        /// <summary>
        /// ID of the unit tested.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Serial number of the unit.
        /// </summary>
        [JsonPropertyName("serial_number")]
        public string SerialNumber { get; set; } = default!;
    }
}