//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System;
    
    public class LogListData
    {

        /// <summary>
        /// Unique identifier for the log entry.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Log level indicating the severity.
        /// </summary>
        [JsonPropertyName("level")]
        public LogListDataLevel Level { get; set; } = default!;

        /// <summary>
        /// The log message content.
        /// </summary>
        [JsonPropertyName("message")]
        public string Message { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the log was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        /// <summary>
        /// Source file where the log originated.
        /// </summary>
        [JsonPropertyName("source_file")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? SourceFile { get; set; }

        /// <summary>
        /// Line number in the source file.
        /// </summary>
        [JsonPropertyName("line_number")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public long? LineNumber { get; set; }

        /// <summary>
        /// Run information for this log entry.
        /// </summary>
        [JsonPropertyName("run")]
        public LogListRun Run { get; set; } = default!;

        /// <summary>
        /// Unit information for this log entry.
        /// </summary>
        [JsonPropertyName("unit")]
        public LogListUnit Unit { get; set; } = default!;

        /// <summary>
        /// Procedure information for this log entry.
        /// </summary>
        [JsonPropertyName("procedure")]
        public LogListProcedure Procedure { get; set; } = default!;

        /// <summary>
        /// User who created this log. Null if created by a station or system.
        /// </summary>
        [JsonPropertyName("created_by_user")]
        public LogListCreatedByUser? CreatedByUser { get; set; } = null;

        /// <summary>
        /// Station that created this log. Null if created by a user.
        /// </summary>
        [JsonPropertyName("created_by_station")]
        public LogListCreatedByStation? CreatedByStation { get; set; } = null;
    }
}