//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Run information for this log entry.
    /// </summary>
    public class LogListRun
    {

        /// <summary>
        /// ID of the run this log belongs to.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Outcome of the run.
        /// </summary>
        [JsonPropertyName("outcome")]
        public LogListOutcome Outcome { get; set; } = default!;

        /// <summary>
        /// When the run started.
        /// </summary>
        [JsonPropertyName("started_at")]
        public DateTime StartedAt { get; set; } = default!;
    }
}