//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    
    public enum MeasurementListQueryParamMeasurementType
    {
        [JsonPropertyName("numeric")]
        Numeric,
        [JsonPropertyName("boolean")]
        Boolean,
        [JsonPropertyName("string")]
        String,
        [JsonPropertyName("multidimensional")]
        Multidimensional,
        [JsonPropertyName("empty")]
        Empty,
        [JsonPropertyName("json")]
        Json,
    }

    public static class MeasurementListQueryParamMeasurementTypeExtension
    {
        public static string Value(this MeasurementListQueryParamMeasurementType value)
        {
            return ((JsonPropertyNameAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyNameAttribute), false)[0]).Name ?? value.ToString();
        }

        public static MeasurementListQueryParamMeasurementType ToEnum(this string value)
        {
            foreach(var field in typeof(MeasurementListQueryParamMeasurementType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyNameAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyNameAttribute;
                if (attribute != null && attribute.Name == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is MeasurementListQueryParamMeasurementType)
                    {
                        return (MeasurementListQueryParamMeasurementType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum MeasurementListQueryParamMeasurementType");
        }
    }

}