//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Measurement retrieved successfully
    /// </summary>
    public class MeasurementGetResponse
    {

        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        [JsonPropertyName("outcome")]
        public MeasurementGetOutcome Outcome { get; set; } = default!;

        [JsonPropertyName("units")]
        public string? Units { get; set; } = null;

        [JsonPropertyName("validators")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public List<MeasurementGetValidators>? Validators { get; set; }

        [JsonPropertyName("aggregations")]
        public List<MeasurementGetAggregations>? Aggregations { get; set; } = null;

        [JsonPropertyName("measured_value")]
        public object? MeasuredValue { get; set; }

        [JsonPropertyName("data_series")]
        public List<MeasurementGetDataSeries>? DataSeries { get; set; }

        [JsonPropertyName("docstring")]
        public string? Docstring { get; set; } = null;

        [JsonPropertyName("phase")]
        public MeasurementGetPhase Phase { get; set; } = default!;

        [JsonPropertyName("run")]
        public MeasurementGetRun Run { get; set; } = default!;

        [JsonPropertyName("procedure")]
        public MeasurementGetProcedure Procedure { get; set; } = default!;
    }
}