//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Sample class of the unit (golden or failing). Null for regular units.
    /// </summary>
    public enum MeasurementListSample
    {
        [JsonPropertyName("golden")]
        Golden,
        [JsonPropertyName("failing")]
        Failing,
    }

    public static class MeasurementListSampleExtension
    {
        public static string Value(this MeasurementListSample value)
        {
            return ((JsonPropertyNameAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyNameAttribute), false)[0]).Name ?? value.ToString();
        }

        public static MeasurementListSample ToEnum(this string value)
        {
            foreach(var field in typeof(MeasurementListSample).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyNameAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyNameAttribute;
                if (attribute != null && attribute.Name == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is MeasurementListSample)
                    {
                        return (MeasurementListSample)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum MeasurementListSample");
        }
    }

}