//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Revision retrieved successfully
    /// </summary>
    public class PartGetRevisionResponse
    {

        /// <summary>
        /// Unique identifier of the revision.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Revision number.
        /// </summary>
        [JsonProperty("number")]
        public string Number { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the revision was created.
        /// </summary>
        [JsonProperty("created_at", NullValueHandling = NullValueHandling.Include)]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// User who created the revision.
        /// </summary>
        [JsonProperty("created_by_user", NullValueHandling = NullValueHandling.Include)]
        public PartGetRevisionCreatedByUser? CreatedByUser { get; set; }

        /// <summary>
        /// Station that created the revision.
        /// </summary>
        [JsonProperty("created_by_station", NullValueHandling = NullValueHandling.Include)]
        public PartGetRevisionCreatedByStation? CreatedByStation { get; set; }

        /// <summary>
        /// Part associated with this revision.
        /// </summary>
        [JsonProperty("part")]
        public PartGetRevisionPart Part { get; set; } = default!;

        /// <summary>
        /// List of units created with this revision.
        /// </summary>
        [JsonProperty("units")]
        public List<PartGetRevisionUnits> Units { get; set; } = default!;
    }
}