//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Parts retrieved successfully
    /// </summary>
    public class PartListResponse
    {

        /// <summary>
        /// List of parts matching the search criteria.
        /// </summary>
        [JsonProperty("data")]
        public List<PartListData> Data { get; set; } = default!;

        /// <summary>
        /// Pagination metadata.
        /// </summary>
        [JsonProperty("meta")]
        public PartListMeta Meta { get; set; } = default!;
    }
}