//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    
    public class PartCreateRequest
    {

        /// <summary>
        /// Unique identifier number for the part.
        /// </summary>
        [JsonProperty("number")]
        public string Number { get; set; } = default!;

        /// <summary>
        /// Human-readable name for the part. If not provided, a default name will be used.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Revision identifier for the part version. If not provided, default revision identifier will be used.
        /// </summary>
        [JsonProperty("revision_number")]
        public string? RevisionNumber { get; set; }
    }
}