//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    
    public class PartUpdateRevisionRequest
    {

        /// <summary>
        /// Part number that the revision belongs to.
        /// </summary>
        [ApiMetadata("pathParam:style=simple,explode=false,name=part_number")]
        public string PartNumber { get; set; } = default!;

        /// <summary>
        /// Current revision number to update.
        /// </summary>
        [ApiMetadata("pathParam:style=simple,explode=false,name=revision_number")]
        public string RevisionNumber { get; set; } = default!;

        [ApiMetadata("request:mediaType=application/json")]
        public PartUpdateRevisionRequestBody RequestBody { get; set; } = default!;
    }
}