//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Part retrieved successfully
    /// </summary>
    public class PartGetResponse
    {

        /// <summary>
        /// Unique identifier for the part.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Part number.
        /// </summary>
        [JsonPropertyName("number")]
        public string Number { get; set; } = default!;

        /// <summary>
        /// Part name.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the part was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        /// <summary>
        /// User who created this part.
        /// </summary>
        [JsonPropertyName("created_by_user")]
        public PartGetCreatedByUser? CreatedByUser { get; set; } = null;

        /// <summary>
        /// Station that created this part.
        /// </summary>
        [JsonPropertyName("created_by_station")]
        public PartGetCreatedByStation? CreatedByStation { get; set; } = null;

        /// <summary>
        /// List of revisions for this part.
        /// </summary>
        [JsonPropertyName("revisions")]
        public List<PartGetRevisions> Revisions { get; set; } = default!;
    }
}