//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    
    public class PartUpdateRequestBody
    {

        /// <summary>
        /// New unique identifier number for the part.
        /// </summary>
        [JsonProperty("new_number")]
        public string? NewNumber { get; set; }

        /// <summary>
        /// New human-readable name for the part.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }
    }
}