//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    
    /// <summary>
    /// Revision created successfully
    /// </summary>
    public class PartCreateRevisionResponse
    {

        /// <summary>
        /// Unique identifier of the created revision.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
    }
}