//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System;
    
    public class PhaseListData
    {

        /// <summary>
        /// Unique identifier for the phase.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Name of the phase.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Outcome of the phase.
        /// </summary>
        [JsonPropertyName("outcome")]
        public PhaseListDataOutcome Outcome { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the phase started.
        /// </summary>
        [JsonPropertyName("started_at")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DateTime? StartedAt { get; set; }

        /// <summary>
        /// ISO 8601 timestamp when the phase ended.
        /// </summary>
        [JsonPropertyName("ended_at")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DateTime? EndedAt { get; set; }

        /// <summary>
        /// Phase duration in milliseconds. Null when start or end is missing.
        /// </summary>
        [JsonPropertyName("duration_ms")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public long? DurationMs { get; set; }

        /// <summary>
        /// Retry attempt number of the phase (0 for the first attempt).
        /// </summary>
        [JsonPropertyName("retry_count")]
        public long RetryCount { get; set; } = default!;

        /// <summary>
        /// True when this is the final attempt of the phase.
        /// </summary>
        [JsonPropertyName("is_final_attempt")]
        public bool IsFinalAttempt { get; set; } = default!;

        /// <summary>
        /// ID of the run this phase belongs to.
        /// </summary>
        [JsonPropertyName("run_id")]
        public string RunId { get; set; } = default!;

        /// <summary>
        /// Outcome of the run this phase belongs to.
        /// </summary>
        [JsonPropertyName("run_outcome")]
        public PhaseListDataRunOutcome RunOutcome { get; set; } = default!;

        /// <summary>
        /// Serial number of the unit tested.
        /// </summary>
        [JsonPropertyName("serial_number")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? SerialNumber { get; set; }

        /// <summary>
        /// Sample class of the unit (golden or failing). Null for regular units.
        /// </summary>
        [JsonPropertyName("sample")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public PhaseListDataSample? Sample { get; set; }
    }
}