//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Sort order direction.
    /// </summary>
    public enum PhaseListSortOrder
    {
        [JsonPropertyName("asc")]
        Asc,
        [JsonPropertyName("desc")]
        Desc,
    }

    public static class PhaseListSortOrderExtension
    {
        public static string Value(this PhaseListSortOrder value)
        {
            return ((JsonPropertyNameAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyNameAttribute), false)[0]).Name ?? value.ToString();
        }

        public static PhaseListSortOrder ToEnum(this string value)
        {
            foreach(var field in typeof(PhaseListSortOrder).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyNameAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyNameAttribute;
                if (attribute != null && attribute.Name == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PhaseListSortOrder)
                    {
                        return (PhaseListSortOrder)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PhaseListSortOrder");
        }
    }

}