//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System.Collections.Generic;
    
    public class PhaseGetMeasurements
    {

        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        [JsonPropertyName("outcome")]
        public PhaseGetMeasurementsOutcome Outcome { get; set; } = default!;

        [JsonPropertyName("units")]
        public string? Units { get; set; } = null;

        [JsonPropertyName("validators")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public List<PhaseGetValidators>? Validators { get; set; }

        [JsonPropertyName("aggregations")]
        public List<PhaseGetAggregations>? Aggregations { get; set; } = null;

        [JsonPropertyName("measured_value")]
        public object? MeasuredValue { get; set; }

        [JsonPropertyName("data_series")]
        public List<PhaseGetDataSeries>? DataSeries { get; set; }

        [JsonPropertyName("docstring")]
        public string? Docstring { get; set; } = null;
    }
}