//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    
    /// <summary>
    /// Pagination metadata.
    /// </summary>
    public class PhaseListMeta
    {

        /// <summary>
        /// Whether more phases are available beyond this page.
        /// </summary>
        [JsonPropertyName("has_more")]
        public bool HasMore { get; set; } = default!;

        /// <summary>
        /// Cursor to fetch the next page. Null when there are no more results.
        /// </summary>
        [JsonPropertyName("next_cursor")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public long? NextCursor { get; set; }
    }
}