//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Result of the test run.
    /// </summary>
    public enum ProcedureListOutcome
    {
        [JsonPropertyName("PASS")]
        Pass,
        [JsonPropertyName("FAIL")]
        Fail,
        [JsonPropertyName("ERROR")]
        Error,
        [JsonPropertyName("TIMEOUT")]
        Timeout,
        [JsonPropertyName("ABORTED")]
        Aborted,
    }

    public static class ProcedureListOutcomeExtension
    {
        public static string Value(this ProcedureListOutcome value)
        {
            return ((JsonPropertyNameAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyNameAttribute), false)[0]).Name ?? value.ToString();
        }

        public static ProcedureListOutcome ToEnum(this string value)
        {
            foreach(var field in typeof(ProcedureListOutcome).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyNameAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyNameAttribute;
                if (attribute != null && attribute.Name == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ProcedureListOutcome)
                    {
                        return (ProcedureListOutcome)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ProcedureListOutcome");
        }
    }

}