//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Procedures retrieved successfully
    /// </summary>
    public class ProcedureListResponse
    {

        [JsonProperty("data")]
        public List<ProcedureListData> Data { get; set; } = default!;

        [JsonProperty("meta")]
        public ProcedureListMeta Meta { get; set; } = default!;
    }
}