//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System;
    
    public class ProcedureListData
    {

        /// <summary>
        /// Unique identifier for the procedure.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Name of the procedure.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the procedure was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        /// <summary>
        /// User who created the procedure.
        /// </summary>
        [JsonPropertyName("created_by_user")]
        public ProcedureListCreatedByUser CreatedByUser { get; set; } = default!;

        /// <summary>
        /// Linked repository for this procedure.
        /// </summary>
        [JsonPropertyName("linkedRepository")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public ProcedureListLinkedRepository? LinkedRepository { get; set; }
    }
}