//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    
    public class ProcedureListData
    {

        /// <summary>
        /// Unique identifier for the procedure.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Name of the procedure.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the procedure was created.
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        /// <summary>
        /// User who created the procedure.
        /// </summary>
        [JsonProperty("created_by_user")]
        public ProcedureListCreatedByUser CreatedByUser { get; set; } = default!;

        /// <summary>
        /// Recent runs for this procedure.
        /// </summary>
        [JsonProperty("runs")]
        public List<ProcedureListRuns> Runs { get; set; } = default!;

        /// <summary>
        /// Linked repository for this procedure.
        /// </summary>
        [JsonProperty("linkedRepository", NullValueHandling = NullValueHandling.Include)]
        public ProcedureListLinkedRepository? LinkedRepository { get; set; }
    }
}