//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using TofuPilot.Utils;
    
    public class ProcedureDeleteVersionRequest
    {

        /// <summary>
        /// ID of the procedure that owns this version
        /// </summary>
        [ApiMetadata("pathParam:style=simple,explode=false,name=procedure_id")]
        public string ProcedureId { get; set; } = default!;

        /// <summary>
        /// Version tag to delete
        /// </summary>
        [ApiMetadata("pathParam:style=simple,explode=false,name=tag")]
        public string Tag { get; set; } = default!;
    }
}