//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System;
    
    public class ProcedureGetRecentRuns
    {

        /// <summary>
        /// Run ID.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the run started.
        /// </summary>
        [JsonPropertyName("started_at")]
        public DateTime StartedAt { get; set; } = default!;

        /// <summary>
        /// Run outcome.
        /// </summary>
        [JsonPropertyName("outcome")]
        public ProcedureGetOutcome Outcome { get; set; } = default!;

        /// <summary>
        /// Unit information.
        /// </summary>
        [JsonPropertyName("unit")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public ProcedureGetUnit? Unit { get; set; }
    }
}