//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Components;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Aggregation specification with computed value and optional validators.
    /// </summary>
    public class RunCreateMeasurementsAggregations
    {

        /// <summary>
        /// Aggregation function: &quot;min&quot;, &quot;max&quot;, &quot;avg&quot;, &quot;sum&quot;, &quot;count&quot;, &quot;std&quot;, &quot;median&quot;, &quot;percentile_95&quot;, etc.
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; } = default!;

        /// <summary>
        /// Computed result of aggregation validation. Server stores as-is.
        /// </summary>
        [JsonPropertyName("outcome")]
        public string? Outcome { get; set; } = null;

        /// <summary>
        /// Computed aggregation value.
        /// </summary>
        [JsonPropertyName("value")]
        public RunCreateMeasurementsValue? Value { get; set; } = null;

        /// <summary>
        /// Unit for the aggregated value.
        /// </summary>
        [JsonPropertyName("unit")]
        public string? Unit { get; set; } = null;

        /// <summary>
        /// Validators applied to the aggregated value.
        /// </summary>
        [JsonPropertyName("validators")]
        public List<RunCreateMeasurementsAggregationsValidators>? Validators { get; set; } = null;
    }
}