//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json;
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class RunCreateMeasurementsValueType
    {
        private RunCreateMeasurementsValueType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RunCreateMeasurementsValueType Number { get { return new RunCreateMeasurementsValueType("number"); } }
        
        public static RunCreateMeasurementsValueType Str { get { return new RunCreateMeasurementsValueType("str"); } }
        
        public static RunCreateMeasurementsValueType Boolean { get { return new RunCreateMeasurementsValueType("boolean"); } }
        
        public static RunCreateMeasurementsValueType Null { get { return new RunCreateMeasurementsValueType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RunCreateMeasurementsValueType v) { return v.Value; }
        public static RunCreateMeasurementsValueType FromString(string v) {
            switch(v) {
                case "number": return Number;
                case "str": return Str;
                case "boolean": return Boolean;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RunCreateMeasurementsValueType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RunCreateMeasurementsValueType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Computed aggregation value.
    /// </summary>
    [JsonConverter(typeof(RunCreateMeasurementsValue.RunCreateMeasurementsValueConverter))]
    public class RunCreateMeasurementsValue {
        public RunCreateMeasurementsValue(RunCreateMeasurementsValueType type) {
            Type = type;
        }

        [ApiMetadata("form:explode=true")]
        public double? Number { get; set; }

        [ApiMetadata("form:explode=true")]
        public string? Str { get; set; }

        [ApiMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        public RunCreateMeasurementsValueType Type { get; set; }


        public static RunCreateMeasurementsValue CreateNumber(double number) {
            RunCreateMeasurementsValueType typ = RunCreateMeasurementsValueType.Number;

            RunCreateMeasurementsValue res = new RunCreateMeasurementsValue(typ);
            res.Number = number;
            return res;
        }

        public static RunCreateMeasurementsValue CreateStr(string str) {
            RunCreateMeasurementsValueType typ = RunCreateMeasurementsValueType.Str;

            RunCreateMeasurementsValue res = new RunCreateMeasurementsValue(typ);
            res.Str = str;
            return res;
        }

        public static RunCreateMeasurementsValue CreateBoolean(bool boolean) {
            RunCreateMeasurementsValueType typ = RunCreateMeasurementsValueType.Boolean;

            RunCreateMeasurementsValue res = new RunCreateMeasurementsValue(typ);
            res.Boolean = boolean;
            return res;
        }

        public static RunCreateMeasurementsValue CreateNull() {
            RunCreateMeasurementsValueType typ = RunCreateMeasurementsValueType.Null;
            return new RunCreateMeasurementsValue(typ);
        }

        public class RunCreateMeasurementsValueConverter : JsonConverter<RunCreateMeasurementsValue>
        {

            public override RunCreateMeasurementsValue? Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options)
            {
                if (reader.TokenType == JsonTokenType.Null)
                {
                    reader.Read();
                    return null;
                }

                using var doc = JsonDocument.ParseValue(ref reader);
                var json = doc.RootElement.GetRawText();

                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new RunCreateMeasurementsValue(RunCreateMeasurementsValueType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new RunCreateMeasurementsValue(RunCreateMeasurementsValueType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new RunCreateMeasurementsValue(RunCreateMeasurementsValueType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return (RunCreateMeasurementsValue)ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void Write(Utf8JsonWriter writer, RunCreateMeasurementsValue? value, JsonSerializerOptions options)
            {
                if (value == null) {
                    writer.WriteNullValue();
                    return;
                }
                if (RunCreateMeasurementsValueType.FromString(value.Type).Equals(RunCreateMeasurementsValueType.Null))
                {
                    writer.WriteNullValue();
                    return;
                }
                if (value.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Number));
                    return;
                }
                if (value.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Str));
                    return;
                }
                if (value.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Boolean));
                    return;
                }

            }

        }

    }
}