//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json;
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class RunCreateYAxisAggregationsExpectedValueType
    {
        private RunCreateYAxisAggregationsExpectedValueType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RunCreateYAxisAggregationsExpectedValueType Boolean { get { return new RunCreateYAxisAggregationsExpectedValueType("boolean"); } }
        
        public static RunCreateYAxisAggregationsExpectedValueType Number { get { return new RunCreateYAxisAggregationsExpectedValueType("number"); } }
        
        public static RunCreateYAxisAggregationsExpectedValueType Str { get { return new RunCreateYAxisAggregationsExpectedValueType("str"); } }
        
        public static RunCreateYAxisAggregationsExpectedValueType ArrayOfNumber { get { return new RunCreateYAxisAggregationsExpectedValueType("arrayOfNumber"); } }
        
        public static RunCreateYAxisAggregationsExpectedValueType ArrayOfStr { get { return new RunCreateYAxisAggregationsExpectedValueType("arrayOfStr"); } }
        
        public static RunCreateYAxisAggregationsExpectedValueType Null { get { return new RunCreateYAxisAggregationsExpectedValueType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RunCreateYAxisAggregationsExpectedValueType v) { return v.Value; }
        public static RunCreateYAxisAggregationsExpectedValueType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "number": return Number;
                case "str": return Str;
                case "arrayOfNumber": return ArrayOfNumber;
                case "arrayOfStr": return ArrayOfStr;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RunCreateYAxisAggregationsExpectedValueType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RunCreateYAxisAggregationsExpectedValueType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Expected value for comparison. Type depends on operator.
    /// </summary>
    [JsonConverter(typeof(RunCreateYAxisAggregationsExpectedValue.RunCreateYAxisAggregationsExpectedValueConverter))]
    public class RunCreateYAxisAggregationsExpectedValue {
        public RunCreateYAxisAggregationsExpectedValue(RunCreateYAxisAggregationsExpectedValueType type) {
            Type = type;
        }

        [ApiMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [ApiMetadata("form:explode=true")]
        public double? Number { get; set; }

        [ApiMetadata("form:explode=true")]
        public string? Str { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<double>? ArrayOfNumber { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<string>? ArrayOfStr { get; set; }

        public RunCreateYAxisAggregationsExpectedValueType Type { get; set; }


        public static RunCreateYAxisAggregationsExpectedValue CreateBoolean(bool boolean) {
            RunCreateYAxisAggregationsExpectedValueType typ = RunCreateYAxisAggregationsExpectedValueType.Boolean;

            RunCreateYAxisAggregationsExpectedValue res = new RunCreateYAxisAggregationsExpectedValue(typ);
            res.Boolean = boolean;
            return res;
        }

        public static RunCreateYAxisAggregationsExpectedValue CreateNumber(double number) {
            RunCreateYAxisAggregationsExpectedValueType typ = RunCreateYAxisAggregationsExpectedValueType.Number;

            RunCreateYAxisAggregationsExpectedValue res = new RunCreateYAxisAggregationsExpectedValue(typ);
            res.Number = number;
            return res;
        }

        public static RunCreateYAxisAggregationsExpectedValue CreateStr(string str) {
            RunCreateYAxisAggregationsExpectedValueType typ = RunCreateYAxisAggregationsExpectedValueType.Str;

            RunCreateYAxisAggregationsExpectedValue res = new RunCreateYAxisAggregationsExpectedValue(typ);
            res.Str = str;
            return res;
        }

        public static RunCreateYAxisAggregationsExpectedValue CreateArrayOfNumber(List<double> arrayOfNumber) {
            RunCreateYAxisAggregationsExpectedValueType typ = RunCreateYAxisAggregationsExpectedValueType.ArrayOfNumber;

            RunCreateYAxisAggregationsExpectedValue res = new RunCreateYAxisAggregationsExpectedValue(typ);
            res.ArrayOfNumber = arrayOfNumber;
            return res;
        }

        public static RunCreateYAxisAggregationsExpectedValue CreateArrayOfStr(List<string> arrayOfStr) {
            RunCreateYAxisAggregationsExpectedValueType typ = RunCreateYAxisAggregationsExpectedValueType.ArrayOfStr;

            RunCreateYAxisAggregationsExpectedValue res = new RunCreateYAxisAggregationsExpectedValue(typ);
            res.ArrayOfStr = arrayOfStr;
            return res;
        }

        public static RunCreateYAxisAggregationsExpectedValue CreateNull() {
            RunCreateYAxisAggregationsExpectedValueType typ = RunCreateYAxisAggregationsExpectedValueType.Null;
            return new RunCreateYAxisAggregationsExpectedValue(typ);
        }

        public class RunCreateYAxisAggregationsExpectedValueConverter : JsonConverter<RunCreateYAxisAggregationsExpectedValue>
        {

            public override RunCreateYAxisAggregationsExpectedValue? Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options)
            {
                if (reader.TokenType == JsonTokenType.Null)
                {
                    reader.Read();
                    return null;
                }

                using var doc = JsonDocument.ParseValue(ref reader);
                var json = doc.RootElement.GetRawText();

                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new RunCreateYAxisAggregationsExpectedValue(RunCreateYAxisAggregationsExpectedValueType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new RunCreateYAxisAggregationsExpectedValue(RunCreateYAxisAggregationsExpectedValueType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new RunCreateYAxisAggregationsExpectedValue(RunCreateYAxisAggregationsExpectedValueType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    return new RunCreateYAxisAggregationsExpectedValue(RunCreateYAxisAggregationsExpectedValueType.ArrayOfNumber)
                    {
                        ArrayOfNumber = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<double>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<double>), new RunCreateYAxisAggregationsExpectedValue(RunCreateYAxisAggregationsExpectedValueType.ArrayOfNumber), "ArrayOfNumber"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new RunCreateYAxisAggregationsExpectedValue(RunCreateYAxisAggregationsExpectedValueType.ArrayOfStr)
                    {
                        ArrayOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<string>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<string>), new RunCreateYAxisAggregationsExpectedValue(RunCreateYAxisAggregationsExpectedValueType.ArrayOfStr), "ArrayOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return (RunCreateYAxisAggregationsExpectedValue)ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void Write(Utf8JsonWriter writer, RunCreateYAxisAggregationsExpectedValue? value, JsonSerializerOptions options)
            {
                if (value == null) {
                    writer.WriteNullValue();
                    return;
                }
                if (RunCreateYAxisAggregationsExpectedValueType.FromString(value.Type).Equals(RunCreateYAxisAggregationsExpectedValueType.Null))
                {
                    writer.WriteNullValue();
                    return;
                }
                if (value.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Boolean));
                    return;
                }
                if (value.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Number));
                    return;
                }
                if (value.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Str));
                    return;
                }
                if (value.ArrayOfNumber != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.ArrayOfNumber));
                    return;
                }
                if (value.ArrayOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.ArrayOfStr));
                    return;
                }

            }

        }

    }
}