//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Data series with numeric data, unit, and optional validators/aggregations.
    /// </summary>
    public class RunCreateXAxis
    {

        /// <summary>
        /// Array of numeric data points for this axis.
        /// </summary>
        [JsonPropertyName("data")]
        public List<double> Data { get; set; } = default!;

        /// <summary>
        /// Unit for this axis.
        /// </summary>
        [JsonPropertyName("units")]
        public string? Units { get; set; } = null;

        /// <summary>
        /// Description of this data series.
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; set; } = null;

        /// <summary>
        /// Validators for this specific axis/series.
        /// </summary>
        [JsonPropertyName("validators")]
        public List<RunCreateValidators>? Validators { get; set; } = null;

        /// <summary>
        /// Aggregations computed over this axis data (min, max, avg, etc.).
        /// </summary>
        [JsonPropertyName("aggregations")]
        public List<RunCreateAggregations>? Aggregations { get; set; } = null;
    }
}