//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class RunCreateMeasurementsAggregationsExpectedValueType
    {
        private RunCreateMeasurementsAggregationsExpectedValueType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RunCreateMeasurementsAggregationsExpectedValueType Boolean { get { return new RunCreateMeasurementsAggregationsExpectedValueType("boolean"); } }
        
        public static RunCreateMeasurementsAggregationsExpectedValueType Number { get { return new RunCreateMeasurementsAggregationsExpectedValueType("number"); } }
        
        public static RunCreateMeasurementsAggregationsExpectedValueType Str { get { return new RunCreateMeasurementsAggregationsExpectedValueType("str"); } }
        
        public static RunCreateMeasurementsAggregationsExpectedValueType ArrayOfNumber { get { return new RunCreateMeasurementsAggregationsExpectedValueType("arrayOfNumber"); } }
        
        public static RunCreateMeasurementsAggregationsExpectedValueType ArrayOfStr { get { return new RunCreateMeasurementsAggregationsExpectedValueType("arrayOfStr"); } }
        
        public static RunCreateMeasurementsAggregationsExpectedValueType Null { get { return new RunCreateMeasurementsAggregationsExpectedValueType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RunCreateMeasurementsAggregationsExpectedValueType v) { return v.Value; }
        public static RunCreateMeasurementsAggregationsExpectedValueType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "number": return Number;
                case "str": return Str;
                case "arrayOfNumber": return ArrayOfNumber;
                case "arrayOfStr": return ArrayOfStr;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RunCreateMeasurementsAggregationsExpectedValueType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RunCreateMeasurementsAggregationsExpectedValueType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Expected value for comparison. Type depends on operator.
    /// </summary>
    [JsonConverter(typeof(RunCreateMeasurementsAggregationsExpectedValue.RunCreateMeasurementsAggregationsExpectedValueConverter))]
    public class RunCreateMeasurementsAggregationsExpectedValue {
        public RunCreateMeasurementsAggregationsExpectedValue(RunCreateMeasurementsAggregationsExpectedValueType type) {
            Type = type;
        }

        [ApiMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [ApiMetadata("form:explode=true")]
        public double? Number { get; set; }

        [ApiMetadata("form:explode=true")]
        public string? Str { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<double>? ArrayOfNumber { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<string>? ArrayOfStr { get; set; }

        public RunCreateMeasurementsAggregationsExpectedValueType Type { get; set; }


        public static RunCreateMeasurementsAggregationsExpectedValue CreateBoolean(bool boolean) {
            RunCreateMeasurementsAggregationsExpectedValueType typ = RunCreateMeasurementsAggregationsExpectedValueType.Boolean;

            RunCreateMeasurementsAggregationsExpectedValue res = new RunCreateMeasurementsAggregationsExpectedValue(typ);
            res.Boolean = boolean;
            return res;
        }

        public static RunCreateMeasurementsAggregationsExpectedValue CreateNumber(double number) {
            RunCreateMeasurementsAggregationsExpectedValueType typ = RunCreateMeasurementsAggregationsExpectedValueType.Number;

            RunCreateMeasurementsAggregationsExpectedValue res = new RunCreateMeasurementsAggregationsExpectedValue(typ);
            res.Number = number;
            return res;
        }

        public static RunCreateMeasurementsAggregationsExpectedValue CreateStr(string str) {
            RunCreateMeasurementsAggregationsExpectedValueType typ = RunCreateMeasurementsAggregationsExpectedValueType.Str;

            RunCreateMeasurementsAggregationsExpectedValue res = new RunCreateMeasurementsAggregationsExpectedValue(typ);
            res.Str = str;
            return res;
        }

        public static RunCreateMeasurementsAggregationsExpectedValue CreateArrayOfNumber(List<double> arrayOfNumber) {
            RunCreateMeasurementsAggregationsExpectedValueType typ = RunCreateMeasurementsAggregationsExpectedValueType.ArrayOfNumber;

            RunCreateMeasurementsAggregationsExpectedValue res = new RunCreateMeasurementsAggregationsExpectedValue(typ);
            res.ArrayOfNumber = arrayOfNumber;
            return res;
        }

        public static RunCreateMeasurementsAggregationsExpectedValue CreateArrayOfStr(List<string> arrayOfStr) {
            RunCreateMeasurementsAggregationsExpectedValueType typ = RunCreateMeasurementsAggregationsExpectedValueType.ArrayOfStr;

            RunCreateMeasurementsAggregationsExpectedValue res = new RunCreateMeasurementsAggregationsExpectedValue(typ);
            res.ArrayOfStr = arrayOfStr;
            return res;
        }

        public static RunCreateMeasurementsAggregationsExpectedValue CreateNull() {
            RunCreateMeasurementsAggregationsExpectedValueType typ = RunCreateMeasurementsAggregationsExpectedValueType.Null;
            return new RunCreateMeasurementsAggregationsExpectedValue(typ);
        }

        public class RunCreateMeasurementsAggregationsExpectedValueConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(RunCreateMeasurementsAggregationsExpectedValue);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new RunCreateMeasurementsAggregationsExpectedValue(RunCreateMeasurementsAggregationsExpectedValueType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new RunCreateMeasurementsAggregationsExpectedValue(RunCreateMeasurementsAggregationsExpectedValueType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new RunCreateMeasurementsAggregationsExpectedValue(RunCreateMeasurementsAggregationsExpectedValueType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    return new RunCreateMeasurementsAggregationsExpectedValue(RunCreateMeasurementsAggregationsExpectedValueType.ArrayOfNumber)
                    {
                        ArrayOfNumber = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<double>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<double>), new RunCreateMeasurementsAggregationsExpectedValue(RunCreateMeasurementsAggregationsExpectedValueType.ArrayOfNumber), "ArrayOfNumber"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new RunCreateMeasurementsAggregationsExpectedValue(RunCreateMeasurementsAggregationsExpectedValueType.ArrayOfStr)
                    {
                        ArrayOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<string>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<string>), new RunCreateMeasurementsAggregationsExpectedValue(RunCreateMeasurementsAggregationsExpectedValueType.ArrayOfStr), "ArrayOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                RunCreateMeasurementsAggregationsExpectedValue res = (RunCreateMeasurementsAggregationsExpectedValue)value;
                if (RunCreateMeasurementsAggregationsExpectedValueType.FromString(res.Type).Equals(RunCreateMeasurementsAggregationsExpectedValueType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.ArrayOfNumber != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfNumber));
                    return;
                }
                if (res.ArrayOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfStr));
                    return;
                }

            }

        }

    }
}