//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class RunCreateExpectedValueType
    {
        private RunCreateExpectedValueType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RunCreateExpectedValueType Boolean { get { return new RunCreateExpectedValueType("boolean"); } }
        
        public static RunCreateExpectedValueType Number { get { return new RunCreateExpectedValueType("number"); } }
        
        public static RunCreateExpectedValueType Str { get { return new RunCreateExpectedValueType("str"); } }
        
        public static RunCreateExpectedValueType ArrayOfNumber { get { return new RunCreateExpectedValueType("arrayOfNumber"); } }
        
        public static RunCreateExpectedValueType ArrayOfStr { get { return new RunCreateExpectedValueType("arrayOfStr"); } }
        
        public static RunCreateExpectedValueType Null { get { return new RunCreateExpectedValueType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RunCreateExpectedValueType v) { return v.Value; }
        public static RunCreateExpectedValueType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "number": return Number;
                case "str": return Str;
                case "arrayOfNumber": return ArrayOfNumber;
                case "arrayOfStr": return ArrayOfStr;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RunCreateExpectedValueType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RunCreateExpectedValueType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Expected value for comparison. Type depends on operator.
    /// </summary>
    [JsonConverter(typeof(RunCreateExpectedValue.RunCreateExpectedValueConverter))]
    public class RunCreateExpectedValue {
        public RunCreateExpectedValue(RunCreateExpectedValueType type) {
            Type = type;
        }

        [ApiMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [ApiMetadata("form:explode=true")]
        public double? Number { get; set; }

        [ApiMetadata("form:explode=true")]
        public string? Str { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<double>? ArrayOfNumber { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<string>? ArrayOfStr { get; set; }

        public RunCreateExpectedValueType Type { get; set; }


        public static RunCreateExpectedValue CreateBoolean(bool boolean) {
            RunCreateExpectedValueType typ = RunCreateExpectedValueType.Boolean;

            RunCreateExpectedValue res = new RunCreateExpectedValue(typ);
            res.Boolean = boolean;
            return res;
        }

        public static RunCreateExpectedValue CreateNumber(double number) {
            RunCreateExpectedValueType typ = RunCreateExpectedValueType.Number;

            RunCreateExpectedValue res = new RunCreateExpectedValue(typ);
            res.Number = number;
            return res;
        }

        public static RunCreateExpectedValue CreateStr(string str) {
            RunCreateExpectedValueType typ = RunCreateExpectedValueType.Str;

            RunCreateExpectedValue res = new RunCreateExpectedValue(typ);
            res.Str = str;
            return res;
        }

        public static RunCreateExpectedValue CreateArrayOfNumber(List<double> arrayOfNumber) {
            RunCreateExpectedValueType typ = RunCreateExpectedValueType.ArrayOfNumber;

            RunCreateExpectedValue res = new RunCreateExpectedValue(typ);
            res.ArrayOfNumber = arrayOfNumber;
            return res;
        }

        public static RunCreateExpectedValue CreateArrayOfStr(List<string> arrayOfStr) {
            RunCreateExpectedValueType typ = RunCreateExpectedValueType.ArrayOfStr;

            RunCreateExpectedValue res = new RunCreateExpectedValue(typ);
            res.ArrayOfStr = arrayOfStr;
            return res;
        }

        public static RunCreateExpectedValue CreateNull() {
            RunCreateExpectedValueType typ = RunCreateExpectedValueType.Null;
            return new RunCreateExpectedValue(typ);
        }

        public class RunCreateExpectedValueConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(RunCreateExpectedValue);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new RunCreateExpectedValue(RunCreateExpectedValueType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new RunCreateExpectedValue(RunCreateExpectedValueType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new RunCreateExpectedValue(RunCreateExpectedValueType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    return new RunCreateExpectedValue(RunCreateExpectedValueType.ArrayOfNumber)
                    {
                        ArrayOfNumber = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<double>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<double>), new RunCreateExpectedValue(RunCreateExpectedValueType.ArrayOfNumber), "ArrayOfNumber"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new RunCreateExpectedValue(RunCreateExpectedValueType.ArrayOfStr)
                    {
                        ArrayOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<string>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<string>), new RunCreateExpectedValue(RunCreateExpectedValueType.ArrayOfStr), "ArrayOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                RunCreateExpectedValue res = (RunCreateExpectedValue)value;
                if (RunCreateExpectedValueType.FromString(res.Type).Equals(RunCreateExpectedValueType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.ArrayOfNumber != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfNumber));
                    return;
                }
                if (res.ArrayOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfStr));
                    return;
                }

            }

        }

    }
}