//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class RunCreateUnitsType
    {
        private RunCreateUnitsType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RunCreateUnitsType Str { get { return new RunCreateUnitsType("str"); } }
        
        public static RunCreateUnitsType ArrayOfStr { get { return new RunCreateUnitsType("arrayOfStr"); } }
        
        public static RunCreateUnitsType Null { get { return new RunCreateUnitsType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RunCreateUnitsType v) { return v.Value; }
        public static RunCreateUnitsType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "arrayOfStr": return ArrayOfStr;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RunCreateUnitsType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RunCreateUnitsType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// [LEGACY for multi-dim] Units of measurement. For structured multi-dimensional, use units within x_axis/y_axis instead.
    /// </summary>
    [JsonConverter(typeof(RunCreateUnits.RunCreateUnitsConverter))]
    public class RunCreateUnits {
        public RunCreateUnits(RunCreateUnitsType type) {
            Type = type;
        }

        [ApiMetadata("form:explode=true")]
        public string? Str { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<string>? ArrayOfStr { get; set; }

        public RunCreateUnitsType Type { get; set; }


        public static RunCreateUnits CreateStr(string str) {
            RunCreateUnitsType typ = RunCreateUnitsType.Str;

            RunCreateUnits res = new RunCreateUnits(typ);
            res.Str = str;
            return res;
        }

        public static RunCreateUnits CreateArrayOfStr(List<string> arrayOfStr) {
            RunCreateUnitsType typ = RunCreateUnitsType.ArrayOfStr;

            RunCreateUnits res = new RunCreateUnits(typ);
            res.ArrayOfStr = arrayOfStr;
            return res;
        }

        public static RunCreateUnits CreateNull() {
            RunCreateUnitsType typ = RunCreateUnitsType.Null;
            return new RunCreateUnits(typ);
        }

        public class RunCreateUnitsConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(RunCreateUnits);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"'){
                    return new RunCreateUnits(RunCreateUnitsType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    return new RunCreateUnits(RunCreateUnitsType.ArrayOfStr)
                    {
                        ArrayOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<string>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<string>), new RunCreateUnits(RunCreateUnitsType.ArrayOfStr), "ArrayOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                RunCreateUnits res = (RunCreateUnits)value;
                if (RunCreateUnitsType.FromString(res.Type).Equals(RunCreateUnitsType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.ArrayOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfStr));
                    return;
                }

            }

        }

    }
}