//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json;
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class RunCreateMeasuredValueType
    {
        private RunCreateMeasuredValueType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RunCreateMeasuredValueType Number { get { return new RunCreateMeasuredValueType("number"); } }
        
        public static RunCreateMeasuredValueType Str { get { return new RunCreateMeasuredValueType("str"); } }
        
        public static RunCreateMeasuredValueType Boolean { get { return new RunCreateMeasuredValueType("boolean"); } }
        
        public static RunCreateMeasuredValueType ArrayOfArrayOfNumber { get { return new RunCreateMeasuredValueType("arrayOfArrayOfNumber"); } }
        
        public static RunCreateMeasuredValueType MapOfAny { get { return new RunCreateMeasuredValueType("mapOfAny"); } }
        
        public static RunCreateMeasuredValueType ArrayOfAny { get { return new RunCreateMeasuredValueType("arrayOfAny"); } }
        
        public static RunCreateMeasuredValueType Null { get { return new RunCreateMeasuredValueType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RunCreateMeasuredValueType v) { return v.Value; }
        public static RunCreateMeasuredValueType FromString(string v) {
            switch(v) {
                case "number": return Number;
                case "str": return Str;
                case "boolean": return Boolean;
                case "arrayOfArrayOfNumber": return ArrayOfArrayOfNumber;
                case "mapOfAny": return MapOfAny;
                case "arrayOfAny": return ArrayOfAny;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RunCreateMeasuredValueType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RunCreateMeasuredValueType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(RunCreateMeasuredValue.RunCreateMeasuredValueConverter))]
    public class RunCreateMeasuredValue {
        public RunCreateMeasuredValue(RunCreateMeasuredValueType type) {
            Type = type;
        }

        [ApiMetadata("form:explode=true")]
        public double? Number { get; set; }

        [ApiMetadata("form:explode=true")]
        public string? Str { get; set; }

        [ApiMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<List<double>>? ArrayOfArrayOfNumber { get; set; }

        [ApiMetadata("form:explode=true")]
        public Dictionary<string, object>? MapOfAny { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<object>? ArrayOfAny { get; set; }

        public RunCreateMeasuredValueType Type { get; set; }


        public static RunCreateMeasuredValue CreateNumber(double number) {
            RunCreateMeasuredValueType typ = RunCreateMeasuredValueType.Number;

            RunCreateMeasuredValue res = new RunCreateMeasuredValue(typ);
            res.Number = number;
            return res;
        }

        public static RunCreateMeasuredValue CreateStr(string str) {
            RunCreateMeasuredValueType typ = RunCreateMeasuredValueType.Str;

            RunCreateMeasuredValue res = new RunCreateMeasuredValue(typ);
            res.Str = str;
            return res;
        }

        public static RunCreateMeasuredValue CreateBoolean(bool boolean) {
            RunCreateMeasuredValueType typ = RunCreateMeasuredValueType.Boolean;

            RunCreateMeasuredValue res = new RunCreateMeasuredValue(typ);
            res.Boolean = boolean;
            return res;
        }

        public static RunCreateMeasuredValue CreateArrayOfArrayOfNumber(List<List<double>> arrayOfArrayOfNumber) {
            RunCreateMeasuredValueType typ = RunCreateMeasuredValueType.ArrayOfArrayOfNumber;

            RunCreateMeasuredValue res = new RunCreateMeasuredValue(typ);
            res.ArrayOfArrayOfNumber = arrayOfArrayOfNumber;
            return res;
        }

        public static RunCreateMeasuredValue CreateMapOfAny(Dictionary<string, object> mapOfAny) {
            RunCreateMeasuredValueType typ = RunCreateMeasuredValueType.MapOfAny;

            RunCreateMeasuredValue res = new RunCreateMeasuredValue(typ);
            res.MapOfAny = mapOfAny;
            return res;
        }

        public static RunCreateMeasuredValue CreateArrayOfAny(List<object> arrayOfAny) {
            RunCreateMeasuredValueType typ = RunCreateMeasuredValueType.ArrayOfAny;

            RunCreateMeasuredValue res = new RunCreateMeasuredValue(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public static RunCreateMeasuredValue CreateNull() {
            RunCreateMeasuredValueType typ = RunCreateMeasuredValueType.Null;
            return new RunCreateMeasuredValue(typ);
        }

        public static implicit operator RunCreateMeasuredValue(double value) => CreateNumber(value);
        public static implicit operator RunCreateMeasuredValue(string value) => CreateStr(value);
        public static implicit operator RunCreateMeasuredValue(bool value) => CreateBoolean(value);

        public class RunCreateMeasuredValueConverter : JsonConverter<RunCreateMeasuredValue>
        {

            public override RunCreateMeasuredValue? Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options)
            {
                if (reader.TokenType == JsonTokenType.Null)
                {
                    reader.Read();
                    return null;
                }

                using var doc = JsonDocument.ParseValue(ref reader);
                var json = doc.RootElement.GetRawText();

                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new RunCreateMeasuredValue(RunCreateMeasuredValueType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new RunCreateMeasuredValue(RunCreateMeasuredValueType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new RunCreateMeasuredValue(RunCreateMeasuredValueType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new RunCreateMeasuredValue(RunCreateMeasuredValueType.ArrayOfArrayOfNumber)
                    {
                        ArrayOfArrayOfNumber = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<List<double>>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<List<double>>), new RunCreateMeasuredValue(RunCreateMeasuredValueType.ArrayOfArrayOfNumber), "ArrayOfArrayOfNumber"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new RunCreateMeasuredValue(RunCreateMeasuredValueType.MapOfAny)
                    {
                        MapOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Dictionary<string, object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Dictionary<string, object>), new RunCreateMeasuredValue(RunCreateMeasuredValueType.MapOfAny), "MapOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new RunCreateMeasuredValue(RunCreateMeasuredValueType.ArrayOfAny)
                    {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object>), new RunCreateMeasuredValue(RunCreateMeasuredValueType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return (RunCreateMeasuredValue)ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void Write(Utf8JsonWriter writer, RunCreateMeasuredValue? value, JsonSerializerOptions options)
            {
                if (value == null) {
                    writer.WriteNullValue();
                    return;
                }
                if (RunCreateMeasuredValueType.FromString(value.Type).Equals(RunCreateMeasuredValueType.Null))
                {
                    writer.WriteNullValue();
                    return;
                }
                if (value.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Number));
                    return;
                }
                if (value.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Str));
                    return;
                }
                if (value.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Boolean));
                    return;
                }
                if (value.ArrayOfArrayOfNumber != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.ArrayOfArrayOfNumber));
                    return;
                }
                if (value.MapOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.MapOfAny));
                    return;
                }
                if (value.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.ArrayOfAny));
                    return;
                }

            }

        }

    }
}