//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Result of the measurement validation. Use PASS when measurement meets all criteria, FAIL when measurement is outside acceptable limits or validation fails, UNSET when no validation was performed.
    /// </summary>
    public enum RunCreateMeasurementsOutcome
    {
        [JsonProperty("PASS")]
        Pass,
        [JsonProperty("FAIL")]
        Fail,
        [JsonProperty("UNSET")]
        Unset,
    }

    public static class RunCreateMeasurementsOutcomeExtension
    {
        public static string Value(this RunCreateMeasurementsOutcome value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static RunCreateMeasurementsOutcome ToEnum(this string value)
        {
            foreach(var field in typeof(RunCreateMeasurementsOutcome).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is RunCreateMeasurementsOutcome)
                    {
                        return (RunCreateMeasurementsOutcome)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum RunCreateMeasurementsOutcome");
        }
    }

}