//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class RunCreateYAxisExpectedValueType
    {
        private RunCreateYAxisExpectedValueType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RunCreateYAxisExpectedValueType Boolean { get { return new RunCreateYAxisExpectedValueType("boolean"); } }
        
        public static RunCreateYAxisExpectedValueType Number { get { return new RunCreateYAxisExpectedValueType("number"); } }
        
        public static RunCreateYAxisExpectedValueType Str { get { return new RunCreateYAxisExpectedValueType("str"); } }
        
        public static RunCreateYAxisExpectedValueType ArrayOfNumber { get { return new RunCreateYAxisExpectedValueType("arrayOfNumber"); } }
        
        public static RunCreateYAxisExpectedValueType ArrayOfStr { get { return new RunCreateYAxisExpectedValueType("arrayOfStr"); } }
        
        public static RunCreateYAxisExpectedValueType Null { get { return new RunCreateYAxisExpectedValueType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RunCreateYAxisExpectedValueType v) { return v.Value; }
        public static RunCreateYAxisExpectedValueType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "number": return Number;
                case "str": return Str;
                case "arrayOfNumber": return ArrayOfNumber;
                case "arrayOfStr": return ArrayOfStr;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RunCreateYAxisExpectedValueType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RunCreateYAxisExpectedValueType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Expected value for comparison. Type depends on operator.
    /// </summary>
    [JsonConverter(typeof(RunCreateYAxisExpectedValue.RunCreateYAxisExpectedValueConverter))]
    public class RunCreateYAxisExpectedValue {
        public RunCreateYAxisExpectedValue(RunCreateYAxisExpectedValueType type) {
            Type = type;
        }

        [ApiMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [ApiMetadata("form:explode=true")]
        public double? Number { get; set; }

        [ApiMetadata("form:explode=true")]
        public string? Str { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<double>? ArrayOfNumber { get; set; }

        [ApiMetadata("form:explode=true")]
        public List<string>? ArrayOfStr { get; set; }

        public RunCreateYAxisExpectedValueType Type { get; set; }


        public static RunCreateYAxisExpectedValue CreateBoolean(bool boolean) {
            RunCreateYAxisExpectedValueType typ = RunCreateYAxisExpectedValueType.Boolean;

            RunCreateYAxisExpectedValue res = new RunCreateYAxisExpectedValue(typ);
            res.Boolean = boolean;
            return res;
        }

        public static RunCreateYAxisExpectedValue CreateNumber(double number) {
            RunCreateYAxisExpectedValueType typ = RunCreateYAxisExpectedValueType.Number;

            RunCreateYAxisExpectedValue res = new RunCreateYAxisExpectedValue(typ);
            res.Number = number;
            return res;
        }

        public static RunCreateYAxisExpectedValue CreateStr(string str) {
            RunCreateYAxisExpectedValueType typ = RunCreateYAxisExpectedValueType.Str;

            RunCreateYAxisExpectedValue res = new RunCreateYAxisExpectedValue(typ);
            res.Str = str;
            return res;
        }

        public static RunCreateYAxisExpectedValue CreateArrayOfNumber(List<double> arrayOfNumber) {
            RunCreateYAxisExpectedValueType typ = RunCreateYAxisExpectedValueType.ArrayOfNumber;

            RunCreateYAxisExpectedValue res = new RunCreateYAxisExpectedValue(typ);
            res.ArrayOfNumber = arrayOfNumber;
            return res;
        }

        public static RunCreateYAxisExpectedValue CreateArrayOfStr(List<string> arrayOfStr) {
            RunCreateYAxisExpectedValueType typ = RunCreateYAxisExpectedValueType.ArrayOfStr;

            RunCreateYAxisExpectedValue res = new RunCreateYAxisExpectedValue(typ);
            res.ArrayOfStr = arrayOfStr;
            return res;
        }

        public static RunCreateYAxisExpectedValue CreateNull() {
            RunCreateYAxisExpectedValueType typ = RunCreateYAxisExpectedValueType.Null;
            return new RunCreateYAxisExpectedValue(typ);
        }

        public class RunCreateYAxisExpectedValueConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(RunCreateYAxisExpectedValue);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new RunCreateYAxisExpectedValue(RunCreateYAxisExpectedValueType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new RunCreateYAxisExpectedValue(RunCreateYAxisExpectedValueType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new RunCreateYAxisExpectedValue(RunCreateYAxisExpectedValueType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    return new RunCreateYAxisExpectedValue(RunCreateYAxisExpectedValueType.ArrayOfNumber)
                    {
                        ArrayOfNumber = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<double>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<double>), new RunCreateYAxisExpectedValue(RunCreateYAxisExpectedValueType.ArrayOfNumber), "ArrayOfNumber"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new RunCreateYAxisExpectedValue(RunCreateYAxisExpectedValueType.ArrayOfStr)
                    {
                        ArrayOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<string>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<string>), new RunCreateYAxisExpectedValue(RunCreateYAxisExpectedValueType.ArrayOfStr), "ArrayOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                RunCreateYAxisExpectedValue res = (RunCreateYAxisExpectedValue)value;
                if (RunCreateYAxisExpectedValueType.FromString(res.Type).Equals(RunCreateYAxisExpectedValueType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.ArrayOfNumber != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfNumber));
                    return;
                }
                if (res.ArrayOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfStr));
                    return;
                }

            }

        }

    }
}