//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class RunCreateValueType
    {
        private RunCreateValueType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RunCreateValueType Number { get { return new RunCreateValueType("number"); } }
        
        public static RunCreateValueType Str { get { return new RunCreateValueType("str"); } }
        
        public static RunCreateValueType Boolean { get { return new RunCreateValueType("boolean"); } }
        
        public static RunCreateValueType Null { get { return new RunCreateValueType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RunCreateValueType v) { return v.Value; }
        public static RunCreateValueType FromString(string v) {
            switch(v) {
                case "number": return Number;
                case "str": return Str;
                case "boolean": return Boolean;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RunCreateValueType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RunCreateValueType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Computed aggregation value.
    /// </summary>
    [JsonConverter(typeof(RunCreateValue.RunCreateValueConverter))]
    public class RunCreateValue {
        public RunCreateValue(RunCreateValueType type) {
            Type = type;
        }

        [ApiMetadata("form:explode=true")]
        public double? Number { get; set; }

        [ApiMetadata("form:explode=true")]
        public string? Str { get; set; }

        [ApiMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        public RunCreateValueType Type { get; set; }


        public static RunCreateValue CreateNumber(double number) {
            RunCreateValueType typ = RunCreateValueType.Number;

            RunCreateValue res = new RunCreateValue(typ);
            res.Number = number;
            return res;
        }

        public static RunCreateValue CreateStr(string str) {
            RunCreateValueType typ = RunCreateValueType.Str;

            RunCreateValue res = new RunCreateValue(typ);
            res.Str = str;
            return res;
        }

        public static RunCreateValue CreateBoolean(bool boolean) {
            RunCreateValueType typ = RunCreateValueType.Boolean;

            RunCreateValue res = new RunCreateValue(typ);
            res.Boolean = boolean;
            return res;
        }

        public static RunCreateValue CreateNull() {
            RunCreateValueType typ = RunCreateValueType.Null;
            return new RunCreateValue(typ);
        }

        public class RunCreateValueConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(RunCreateValue);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new RunCreateValue(RunCreateValueType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new RunCreateValue(RunCreateValueType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new RunCreateValue(RunCreateValueType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                RunCreateValue res = (RunCreateValue)value;
                if (RunCreateValueType.FromString(res.Type).Equals(RunCreateValueType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

            }

        }

    }
}