//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Components;
    using TofuPilot.Utils;
    
    /// <summary>
    /// Structured validator specification with operator and expected value.
    /// </summary>
    public class RunCreateValidators
    {

        /// <summary>
        /// Pre-computed validation result from test framework. Server stores as-is, does not re-evaluate.
        /// </summary>
        [JsonProperty("outcome")]
        public string? Outcome { get; set; } = null;

        /// <summary>
        /// Comparison operator: &quot;&gt;&quot;, &quot;&gt;=&quot;, &quot;&lt;&quot;, &quot;&lt;=&quot;, &quot;==&quot;, &quot;!=&quot;, &quot;matches&quot;, &quot;in&quot;, &quot;range&quot;
        /// </summary>
        [JsonProperty("operator")]
        public string? Operator { get; set; } = null;

        /// <summary>
        /// Expected value for comparison. Type depends on operator.
        /// </summary>
        [JsonProperty("expected_value")]
        public RunCreateExpectedValue? ExpectedValue { get; set; } = null;

        /// <summary>
        /// Original expression string for display/audit purposes.
        /// </summary>
        [JsonProperty("expression")]
        public string? Expression { get; set; } = null;

        /// <summary>
        /// Whether this validator is decisive (if it fails, measurement fails). False for marginal/warning validators. Defaults to true.
        /// </summary>
        [JsonProperty("is_decisive")]
        public bool? IsDecisive { get; set; } = null;
    }
}