//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    
    /// <summary>
    /// Validator result with outcome and comparison details.
    /// </summary>
    public class RunGetDataSeriesAggregationsValidators
    {

        /// <summary>
        /// Validation result: PASS, FAIL, or UNSET.
        /// </summary>
        [JsonProperty("outcome")]
        public RunGetDataSeriesAggregationsValidatorsOutcome Outcome { get; set; } = default!;

        /// <summary>
        /// Comparison operator used for validation.
        /// </summary>
        [JsonProperty("operator", NullValueHandling = NullValueHandling.Include)]
        public string? Operator { get; set; }

        /// <summary>
        /// Expected value for comparison. Type depends on measurement type.
        /// </summary>
        [JsonProperty("expected_value", NullValueHandling = NullValueHandling.Include)]
        public object? ExpectedValue { get; set; }

        /// <summary>
        /// Human-readable expression string for display.
        /// </summary>
        [JsonProperty("expression")]
        public string Expression { get; set; } = default!;

        /// <summary>
        /// Whether this validator is decisive (if it fails, measurement fails). False for marginal/warning validators.
        /// </summary>
        [JsonProperty("is_decisive", NullValueHandling = NullValueHandling.Include)]
        public bool? IsDecisive { get; set; }

        /// <summary>
        /// True if validator only has expression (no structured operator/expected_value).
        /// </summary>
        [JsonProperty("is_expression_only")]
        public bool IsExpressionOnly { get; set; } = default!;

        /// <summary>
        /// Synthetic expression from operator+expected_value for analytics tooltip. Null if expression-only.
        /// </summary>
        [JsonProperty("analytics_expression", NullValueHandling = NullValueHandling.Include)]
        public string? AnalyticsExpression { get; set; }

        /// <summary>
        /// True if user provided a custom expression (shown in italic with analytics tooltip).
        /// </summary>
        [JsonProperty("has_custom_expression")]
        public bool HasCustomExpression { get; set; } = default!;
    }
}