//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    
    /// <summary>
    /// Validator result with outcome and comparison details.
    /// </summary>
    public class RunGetDataSeriesValidators
    {

        /// <summary>
        /// Validation result: PASS, FAIL, or UNSET.
        /// </summary>
        [JsonPropertyName("outcome")]
        public RunGetDataSeriesValidatorsOutcome Outcome { get; set; } = default!;

        /// <summary>
        /// Comparison operator used for validation.
        /// </summary>
        [JsonPropertyName("operator")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? Operator { get; set; }

        /// <summary>
        /// Expected value for comparison. Type depends on measurement type.
        /// </summary>
        [JsonPropertyName("expected_value")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public object? ExpectedValue { get; set; }

        /// <summary>
        /// Human-readable expression string for display.
        /// </summary>
        [JsonPropertyName("expression")]
        public string Expression { get; set; } = default!;

        /// <summary>
        /// Whether this validator is decisive (if it fails, measurement fails). False for marginal/warning validators.
        /// </summary>
        [JsonPropertyName("is_decisive")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public bool? IsDecisive { get; set; }

        /// <summary>
        /// True if validator only has expression (no structured operator/expected_value).
        /// </summary>
        [JsonPropertyName("is_expression_only")]
        public bool IsExpressionOnly { get; set; } = default!;

        /// <summary>
        /// Synthetic expression from operator+expected_value for analytics tooltip. Null if expression-only.
        /// </summary>
        [JsonPropertyName("analytics_expression")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? AnalyticsExpression { get; set; }

        /// <summary>
        /// True if user provided a custom expression (shown in italic with analytics tooltip).
        /// </summary>
        [JsonPropertyName("has_custom_expression")]
        public bool HasCustomExpression { get; set; } = default!;
    }
}