//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    
    /// <summary>
    /// Test procedure associated with this run.
    /// </summary>
    public class RunGetProcedure
    {

        /// <summary>
        /// Procedure ID.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Procedure name.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Version of the procedure used for this run.
        /// </summary>
        [JsonProperty("version", NullValueHandling = NullValueHandling.Include)]
        public RunGetVersion? Version { get; set; }
    }
}