//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    using System;
    
    public enum RunGetLevel
    {
        [JsonProperty("DEBUG")]
        Debug,
        [JsonProperty("INFO")]
        Info,
        [JsonProperty("WARNING")]
        Warning,
        [JsonProperty("ERROR")]
        Error,
        [JsonProperty("CRITICAL")]
        Critical,
    }

    public static class RunGetLevelExtension
    {
        public static string Value(this RunGetLevel value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static RunGetLevel ToEnum(this string value)
        {
            foreach(var field in typeof(RunGetLevel).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is RunGetLevel)
                    {
                        return (RunGetLevel)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum RunGetLevel");
        }
    }

}