//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json;
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class RunGetValueType
    {
        private RunGetValueType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RunGetValueType Number { get { return new RunGetValueType("number"); } }
        
        public static RunGetValueType Str { get { return new RunGetValueType("str"); } }
        
        public static RunGetValueType Boolean { get { return new RunGetValueType("boolean"); } }
        
        public static RunGetValueType Null { get { return new RunGetValueType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RunGetValueType v) { return v.Value; }
        public static RunGetValueType FromString(string v) {
            switch(v) {
                case "number": return Number;
                case "str": return Str;
                case "boolean": return Boolean;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RunGetValueType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RunGetValueType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Computed aggregation value. Type depends on aggregation type.
    /// </summary>
    [JsonConverter(typeof(RunGetValue.RunGetValueConverter))]
    public class RunGetValue {
        public RunGetValue(RunGetValueType type) {
            Type = type;
        }

        [ApiMetadata("form:explode=true")]
        public double? Number { get; set; }

        [ApiMetadata("form:explode=true")]
        public string? Str { get; set; }

        [ApiMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        public RunGetValueType Type { get; set; }


        public static RunGetValue CreateNumber(double number) {
            RunGetValueType typ = RunGetValueType.Number;

            RunGetValue res = new RunGetValue(typ);
            res.Number = number;
            return res;
        }

        public static RunGetValue CreateStr(string str) {
            RunGetValueType typ = RunGetValueType.Str;

            RunGetValue res = new RunGetValue(typ);
            res.Str = str;
            return res;
        }

        public static RunGetValue CreateBoolean(bool boolean) {
            RunGetValueType typ = RunGetValueType.Boolean;

            RunGetValue res = new RunGetValue(typ);
            res.Boolean = boolean;
            return res;
        }

        public static RunGetValue CreateNull() {
            RunGetValueType typ = RunGetValueType.Null;
            return new RunGetValue(typ);
        }

        public class RunGetValueConverter : JsonConverter<RunGetValue>
        {

            public override RunGetValue? Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options)
            {
                if (reader.TokenType == JsonTokenType.Null)
                {
                    reader.Read();
                    return null;
                }

                using var doc = JsonDocument.ParseValue(ref reader);
                var json = doc.RootElement.GetRawText();

                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new RunGetValue(RunGetValueType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new RunGetValue(RunGetValueType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new RunGetValue(RunGetValueType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return (RunGetValue)ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void Write(Utf8JsonWriter writer, RunGetValue? value, JsonSerializerOptions options)
            {
                if (value == null) {
                    writer.WriteNullValue();
                    return;
                }
                if (RunGetValueType.FromString(value.Type).Equals(RunGetValueType.Null))
                {
                    writer.WriteNullValue();
                    return;
                }
                if (value.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Number));
                    return;
                }
                if (value.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Str));
                    return;
                }
                if (value.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(value.Boolean));
                    return;
                }

            }

        }

    }
}