//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    using System.Collections.Generic;
    
    public class RunGetDataSeries
    {

        [JsonProperty("data")]
        public List<double> Data { get; set; } = default!;

        [JsonProperty("units", NullValueHandling = NullValueHandling.Include)]
        public string? Units { get; set; }

        [JsonProperty("validators")]
        public List<RunGetDataSeriesValidators>? Validators { get; set; } = null;

        [JsonProperty("aggregations")]
        public List<RunGetDataSeriesAggregations>? Aggregations { get; set; } = null;
    }
}