//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    
    public class RunGetSubUnits
    {

        /// <summary>
        /// Unit ID.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Unit serial number.
        /// </summary>
        [JsonProperty("serial_number")]
        public string SerialNumber { get; set; } = default!;

        /// <summary>
        /// Part number of the sub-unit.
        /// </summary>
        [JsonProperty("part_number")]
        public string PartNumber { get; set; } = default!;

        /// <summary>
        /// Part name of the sub-unit.
        /// </summary>
        [JsonProperty("part_name", NullValueHandling = NullValueHandling.Include)]
        public string? PartName { get; set; }
    }
}