//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Final result of the run execution.
    /// </summary>
    public enum RunListDataOutcome
    {
        [JsonProperty("PASS")]
        Pass,
        [JsonProperty("FAIL")]
        Fail,
        [JsonProperty("ERROR")]
        Error,
        [JsonProperty("TIMEOUT")]
        Timeout,
        [JsonProperty("ABORTED")]
        Aborted,
    }

    public static class RunListDataOutcomeExtension
    {
        public static string Value(this RunListDataOutcome value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static RunListDataOutcome ToEnum(this string value)
        {
            foreach(var field in typeof(RunListDataOutcome).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is RunListDataOutcome)
                    {
                        return (RunListDataOutcome)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum RunListDataOutcome");
        }
    }

}