//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    
    public class StationGetCurrentDeployment
    {

        /// <summary>
        /// When the procedure was deployed
        /// </summary>
        [JsonProperty("deployed_at")]
        public string DeployedAt { get; set; } = default!;

        [JsonProperty("commit", NullValueHandling = NullValueHandling.Include)]
        public StationGetCurrentCommit? Commit { get; set; }

        [JsonProperty("repository", NullValueHandling = NullValueHandling.Include)]
        public StationGetCurrentRepository? Repository { get; set; }
    }
}