//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    
    public class StationGetCommit
    {

        /// <summary>
        /// Git commit SHA
        /// </summary>
        [JsonProperty("sha")]
        public string Sha { get; set; } = default!;

        /// <summary>
        /// Git commit message
        /// </summary>
        [JsonProperty("message")]
        public string Message { get; set; } = default!;

        /// <summary>
        /// Git branch name
        /// </summary>
        [JsonProperty("branch", NullValueHandling = NullValueHandling.Include)]
        public string? Branch { get; set; }
    }
}