//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    
    public class StationGetCurrentProcedures
    {

        /// <summary>
        /// Procedure ID
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Procedure identifier
        /// </summary>
        [JsonPropertyName("identifier")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? Identifier { get; set; }

        /// <summary>
        /// Procedure name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Number of runs created by this station in the last 7 days
        /// </summary>
        [JsonPropertyName("runs_count")]
        public double RunsCount { get; set; } = default!;

        /// <summary>
        /// Deployment information for this procedure on this station
        /// </summary>
        [JsonPropertyName("deployment")]
        public StationGetCurrentDeployment? Deployment { get; set; } = null;
    }
}