//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    
    public class StationGetRepository
    {

        /// <summary>
        /// Repository owner
        /// </summary>
        [JsonPropertyName("owner")]
        public string Owner { get; set; } = default!;

        /// <summary>
        /// Repository name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Git provider
        /// </summary>
        [JsonPropertyName("provider")]
        public StationGetProvider Provider { get; set; } = default!;

        /// <summary>
        /// GitLab project ID (only for GitLab repos)
        /// </summary>
        [JsonPropertyName("gitlab_project_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public double? GitlabProjectId { get; set; }
    }
}