//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    
    public class StationListProcedures
    {

        /// <summary>
        /// Procedure ID
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Procedure identifier
        /// </summary>
        [JsonProperty("identifier", NullValueHandling = NullValueHandling.Include)]
        public string? Identifier { get; set; }

        /// <summary>
        /// Procedure name
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;
    }
}