//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    
    public class StationGetDeployment
    {

        /// <summary>
        /// When the procedure was deployed
        /// </summary>
        [JsonPropertyName("deployed_at")]
        public string DeployedAt { get; set; } = default!;

        [JsonPropertyName("commit")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public StationGetCommit? Commit { get; set; }

        [JsonPropertyName("repository")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public StationGetRepository? Repository { get; set; }
    }
}