//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Git provider
    /// </summary>
    public enum StationGetProvider
    {
        [JsonProperty("github")]
        Github,
        [JsonProperty("gitlab")]
        Gitlab,
    }

    public static class StationGetProviderExtension
    {
        public static string Value(this StationGetProvider value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static StationGetProvider ToEnum(this string value)
        {
            foreach(var field in typeof(StationGetProvider).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is StationGetProvider)
                    {
                        return (StationGetProvider)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum StationGetProvider");
        }
    }

}