//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Current station retrieved successfully
    /// </summary>
    public class StationGetCurrentResponse
    {

        /// <summary>
        /// Unique identifier of the station
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Name of the station
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// API key prefix for the station (full key only shown on creation)
        /// </summary>
        [JsonProperty("api_key", NullValueHandling = NullValueHandling.Include)]
        public string? ApiKey { get; set; }

        /// <summary>
        /// Procedures linked to this station with recent run counts
        /// </summary>
        [JsonProperty("procedures")]
        public List<StationGetCurrentProcedures> Procedures { get; set; } = default!;

        /// <summary>
        /// Slug of the organization this station belongs to
        /// </summary>
        [JsonProperty("organization_slug")]
        public string OrganizationSlug { get; set; } = default!;

        /// <summary>
        /// Current connection status of the station
        /// </summary>
        [JsonProperty("connection_status", NullValueHandling = NullValueHandling.Include)]
        public string? ConnectionStatus { get; set; }

        /// <summary>
        /// Team this station is assigned to
        /// </summary>
        [JsonProperty("team", NullValueHandling = NullValueHandling.Include)]
        public StationGetCurrentTeam? Team { get; set; }
    }
}