//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    
    /// <summary>
    /// Station removed successfully
    /// </summary>
    public class StationRemoveResponse
    {

        /// <summary>
        /// Unique identifier of the removed station
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;
    }
}