//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    using System;
    
    public class UnitListLastRun
    {

        /// <summary>
        /// Unique identifier for the run.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Final result of the test run execution.
        /// </summary>
        [JsonPropertyName("outcome")]
        public UnitListLastRunOutcome Outcome { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the run execution started.
        /// </summary>
        [JsonPropertyName("started_at")]
        public DateTime StartedAt { get; set; } = default!;

        /// <summary>
        /// ISO 8601 timestamp when the run execution completed. Null if still running.
        /// </summary>
        [JsonPropertyName("ended_at")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public DateTime? EndedAt { get; set; }

        /// <summary>
        /// Test procedure that was executed. Null if run had no associated procedure.
        /// </summary>
        [JsonPropertyName("procedure")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public UnitListProcedure? Procedure { get; set; }
    }
}