//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    
    /// <summary>
    /// Part information with the specific revision this unit is built from.
    /// </summary>
    public class UnitListPart
    {

        /// <summary>
        /// Unique identifier for the part.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Part number.
        /// </summary>
        [JsonPropertyName("number")]
        public string Number { get; set; } = default!;

        /// <summary>
        /// Human-readable part name.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Revision information for this part. Every unit must have a specific revision.
        /// </summary>
        [JsonPropertyName("revision")]
        public UnitListRevision Revision { get; set; } = default!;
    }
}