//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System.Collections.Generic;
    
    public class UnitUpdateRequestBody
    {

        /// <summary>
        /// New serial number for the unit.
        /// </summary>
        [JsonPropertyName("new_serial_number")]
        public string? NewSerialNumber { get; set; }

        /// <summary>
        /// New part number for the unit.
        /// </summary>
        [JsonPropertyName("part_number")]
        public string? PartNumber { get; set; }

        /// <summary>
        /// New revision number for the unit.
        /// </summary>
        [JsonPropertyName("revision_number")]
        public string? RevisionNumber { get; set; }

        /// <summary>
        /// New batch number for the unit. Set to null to remove batch.
        /// </summary>
        [JsonPropertyName("batch_number")]
        public string? BatchNumber { get; set; } = null;

        /// <summary>
        /// Array of upload IDs to attach to the unit.
        /// </summary>
        [JsonPropertyName("attachments")]
        public List<string>? Attachments { get; set; }
    }
}