//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    
    public class UnitAddChildRequestBody
    {

        /// <summary>
        /// Serial number of the sub-unit to add
        /// </summary>
        [JsonPropertyName("child_serial_number")]
        public string ChildSerialNumber { get; set; } = default!;
    }
}