//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Field to sort results by. last_run_at sorts by most recent test run date. last_run_procedure sorts by procedure name of the last run.
    /// </summary>
    public enum UnitListSortBy
    {
        [JsonProperty("serial_number")]
        SerialNumber,
        [JsonProperty("created_at")]
        CreatedAt,
        [JsonProperty("last_run_at")]
        LastRunAt,
        [JsonProperty("part_number")]
        PartNumber,
        [JsonProperty("last_run_procedure")]
        LastRunProcedure,
    }

    public static class UnitListSortByExtension
    {
        public static string Value(this UnitListSortBy value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static UnitListSortBy ToEnum(this string value)
        {
            foreach(var field in typeof(UnitListSortBy).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is UnitListSortBy)
                    {
                        return (UnitListSortBy)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum UnitListSortBy");
        }
    }

}