//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    
    public class UnitGetAttachments
    {

        /// <summary>
        /// Attachment ID.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// File name.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// File size in bytes.
        /// </summary>
        [JsonProperty("size", NullValueHandling = NullValueHandling.Include)]
        public double? Size { get; set; }

        /// <summary>
        /// MIME type of the file.
        /// </summary>
        [JsonProperty("content_type", NullValueHandling = NullValueHandling.Include)]
        public string? ContentType { get; set; }

        /// <summary>
        /// Presigned URL for downloading the file. This URL is temporary and will expire.
        /// </summary>
        [JsonProperty("download_url", NullValueHandling = NullValueHandling.Include)]
        public string? DownloadUrl { get; set; }
    }
}