//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Models.Requests;
    using global::TofuPilot.Utils;
    
    public class UnitGetChildrenPart
    {

        /// <summary>
        /// Part ID.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Part number.
        /// </summary>
        [JsonPropertyName("number")]
        public string Number { get; set; } = default!;

        /// <summary>
        /// Part name.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Part revision information.
        /// </summary>
        [JsonPropertyName("revision")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public UnitGetChildrenPartRevision? Revision { get; set; }
    }
}