//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    
    public enum UnitListQueryParamSample
    {
        [JsonPropertyName("golden")]
        Golden,
        [JsonPropertyName("failing")]
        Failing,
        [JsonPropertyName("ignored")]
        Ignored,
    }

    public static class UnitListQueryParamSampleExtension
    {
        public static string Value(this UnitListQueryParamSample value)
        {
            return ((JsonPropertyNameAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyNameAttribute), false)[0]).Name ?? value.ToString();
        }

        public static UnitListQueryParamSample ToEnum(this string value)
        {
            foreach(var field in typeof(UnitListQueryParamSample).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyNameAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyNameAttribute;
                if (attribute != null && attribute.Name == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is UnitListQueryParamSample)
                    {
                        return (UnitListQueryParamSample)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum UnitListQueryParamSample");
        }
    }

}