//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Field to sort results by. last_run_at sorts by most recent test run date. last_run_procedure sorts by procedure name of the last run.
    /// </summary>
    public enum UnitListSortBy
    {
        [JsonPropertyName("serial_number")]
        SerialNumber,
        [JsonPropertyName("created_at")]
        CreatedAt,
        [JsonPropertyName("last_run_at")]
        LastRunAt,
        [JsonPropertyName("part_number")]
        PartNumber,
        [JsonPropertyName("last_run_procedure")]
        LastRunProcedure,
    }

    public static class UnitListSortByExtension
    {
        public static string Value(this UnitListSortBy value)
        {
            return ((JsonPropertyNameAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyNameAttribute), false)[0]).Name ?? value.ToString();
        }

        public static UnitListSortBy ToEnum(this string value)
        {
            foreach(var field in typeof(UnitListSortBy).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyNameAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyNameAttribute;
                if (attribute != null && attribute.Name == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is UnitListSortBy)
                    {
                        return (UnitListSortBy)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum UnitListSortBy");
        }
    }

}