//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    using System;
    
    /// <summary>
    /// Sample classification. &apos;golden&apos; marks a known-good reference unit; &apos;failing&apos; marks a known-faulty reference unit; &apos;ignored&apos; marks a bench-check unit excluded from analytics and alerts. All are excluded from production analytics by default. Set to null to clear and treat as a production unit.
    /// </summary>
    public enum UnitUpdateSample
    {
        [JsonPropertyName("golden")]
        Golden,
        [JsonPropertyName("failing")]
        Failing,
        [JsonPropertyName("ignored")]
        Ignored,
    }

    public static class UnitUpdateSampleExtension
    {
        public static string Value(this UnitUpdateSample value)
        {
            return ((JsonPropertyNameAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyNameAttribute), false)[0]).Name ?? value.ToString();
        }

        public static UnitUpdateSample ToEnum(this string value)
        {
            foreach(var field in typeof(UnitUpdateSample).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyNameAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyNameAttribute;
                if (attribute != null && attribute.Name == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is UnitUpdateSample)
                    {
                        return (UnitUpdateSample)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum UnitUpdateSample");
        }
    }

}