//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using global::TofuPilot.Utils;
    using System.Collections.Generic;
    
    public class UnitDeleteAttachmentRequest
    {

        /// <summary>
        /// Serial number of the unit. Matched case-insensitively.
        /// </summary>
        [ApiMetadata("pathParam:style=simple,explode=false,name=serial_number")]
        public string SerialNumber { get; set; } = default!;

        /// <summary>
        /// Attachment IDs to delete
        /// </summary>
        [ApiMetadata("queryParam:style=form,explode=true,name=ids")]
        public List<string> Ids { get; set; } = default!;
    }
}