//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Models.Requests;
    using TofuPilot.Utils;
    
    public class UnitGetParent
    {

        /// <summary>
        /// Unit ID.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Unit serial number.
        /// </summary>
        [JsonProperty("serial_number")]
        public string SerialNumber { get; set; } = default!;

        /// <summary>
        /// Part information for the parent unit.
        /// </summary>
        [JsonProperty("part", NullValueHandling = NullValueHandling.Include)]
        public UnitGetParentPart? Part { get; set; }
    }
}