//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    
    public class UnitListCreatedByUser
    {

        /// <summary>
        /// Unique identifier for the user.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Display name of the user who created this unit.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Include)]
        public string? Name { get; set; }
    }
}