//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Requests
{
    using System.Text.Json.Serialization;
    using global::TofuPilot.Utils;
    
    /// <summary>
    /// Users retrieved successfully
    /// </summary>
    public class UserListResponse
    {

        /// <summary>
        /// Unique identifier for the user.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Email address of the user.
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; } = default!;

        /// <summary>
        /// Display name of the user.
        /// </summary>
        [JsonPropertyName("name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? Name { get; set; }

        /// <summary>
        /// Profile image URL for the user.
        /// </summary>
        [JsonPropertyName("image")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        public string? Image { get; set; }

        /// <summary>
        /// Whether the user is banned.
        /// </summary>
        [JsonPropertyName("banned")]
        public bool Banned { get; set; } = default!;
    }
}