//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by OpenAPI SDK Generator. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace TofuPilot.Models.Components
{
    using Newtonsoft.Json;
    using TofuPilot.Utils;
    
    public class ErrorBADREQUESTIssue
    {

        [JsonProperty("message")]
        public string Message { get; set; } = default!;
    }
}